// frontend/components/Card.vue
<template>
  <div>
    <img
      class="object-cover w-full h-50 rounded-lg lg:w-64"
      :src="feed.page_img !== 'false' ? feed.page_img : require('~/assets/noimage.png')"
    >
    <div class="flex flex-col justify-between py-2 lg:mx-6">
      <span class="text-sm text-gray-500 dark:text-gray-300">{{feed.site_title}}</span>
      <a
        :href="feed.page_link"
        class="text-xl font-semibold text-gray-800 hover:underline dark:text-white"
        target='_blank'
        rel='noreferrer nofollow noopener'
      >
          {{feed.page_title}}
      </a>
      <span class="text-sm text-gray-500 dark:text-gray-300 text-right">{{feed.created_at}}</span>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'Card',
  props: {
    feed: {
      type: Object,
      required: true
    }
  }
})
</script>

// frontend/components/Card.tsx
import Link from 'next/link';
import { News } from '../types';

type Props = {
  news: News
}

export default function Card({ news }: Props) {
  return (
    <>
      <div className='rounded overflow-hidden shadow-lg'>
        <Link href={news.pageLink} passHref>
          <a className='rounded overflow-hidden shadow-lg' target='_blank' rel='noreferrer nofollow noopener'>
            <img src={news.pageImg !== 'false' ? news.pageImg : '/noimage.png'} alt='' className='w-full object-cover' />
            <div className='px-6 py-4'>
              {news.pageTitle}
            </div>
          </a>
        </Link>
      </div>
    </>
  )
}
